openapi: 3.0.1
info:
  version:  0.0.1
  title: ciao
  description: |-
    Do some math

paths:
  /max:
    post:
      operationId: tdd_course.utils.maximum
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: numbers
              type: array
              items:
                type: integer
      responses:
        '200':
           description: the maximum number
           content:
             application/json:
               schema:
                 type: integer

