openapi: 3.0.1
info:
  version:  0.0.1
  title: ciao
  description: |-
    Do some math

paths:
  /maximum:
    post:
      operationId: api.get_maximum
      requestBody:
        content:
          application/json:
            schema:
              properties:
                numbers:
                  type: array
                  items:
                    type: integer
                  minItems: 1
      responses:
        '200':
           description: the maximum number
           content:
             application/json:
               schema:
                 type: integer

